/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/user': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAllUsers'];
    put?: never;
    post: operations['createUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['updateUser'];
    trace?: never;
  };
  '/supplier': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAllSuppliers'];
    put?: never;
    post: operations['createSupplier'];
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['updateSupplier'];
    trace?: never;
  };
  '/project': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAllProjects'];
    put?: never;
    post: operations['createProject'];
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['updateProject'];
    trace?: never;
  };
  '/process': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAllProcesses'];
    put?: never;
    post: operations['createProcess'];
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['updateProcess'];
    trace?: never;
  };
  '/document/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['uploadFile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/component': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAllComponents'];
    put?: never;
    post: operations['createComponent'];
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['updateComponent'];
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['refreshToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getUserById'];
    put?: never;
    post?: never;
    delete: operations['deleteUser'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/supplier/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getSupplierById'];
    put?: never;
    post?: never;
    delete: operations['deleteSupplier'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/project/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getProjectById'];
    put?: never;
    post?: never;
    delete: operations['deleteProject'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/process/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getProcessById'];
    put?: never;
    post?: never;
    delete: operations['deleteProcess'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/document': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAllDocuments'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/document/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getDocumentById'];
    put?: never;
    post?: never;
    delete: operations['delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/document/{id}/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['previewFile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/document/{id}/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['downloadFile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/component/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getComponentById'];
    put?: never;
    post?: never;
    delete: operations['deleteComponent'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateUserRequest: {
      username: string;
      password: string;
      name?: string;
      surname?: string;
      email: string;
      disable: boolean;
      /** @enum {string} */
      role: 'ROLE_USER' | 'ROLE_ADMIN' | 'ROLE_MANAGER';
    };
    UserDto: {
      /** Format: int64 */
      id?: number;
      /** Format: date-time */
      creationDate?: string;
      /** Format: date-time */
      updateDate?: string;
      username?: string;
      name?: string;
      surname?: string;
      email?: string;
      disable?: boolean;
      /** @enum {string} */
      role?: 'ROLE_USER' | 'ROLE_ADMIN' | 'ROLE_MANAGER';
    };
    CreateSupplierRequest: {
      name: string;
      street: string;
      city: string;
      province: string;
      country: string;
      phoneNumber: string;
      emailAddress: string;
      disable: boolean;
      processesIds?: number[];
    };
    ProcessDto: {
      /** Format: int64 */
      id?: number;
      /** Format: date-time */
      creationDate?: string;
      /** Format: date-time */
      updateDate?: string;
      name?: string;
      description?: string;
      disable?: boolean;
    };
    SupplierDto: {
      /** Format: int64 */
      id?: number;
      /** Format: date-time */
      creationDate?: string;
      /** Format: date-time */
      updateDate?: string;
      name?: string;
      street?: string;
      city?: string;
      province?: string;
      country?: string;
      phoneNumber?: string;
      emailAddress?: string;
      disable?: boolean;
      processes?: components['schemas']['ProcessDto'][];
    };
    CreateProjectRequest: {
      /** Format: date-time */
      validFrom: string;
      /** Format: date-time */
      validTo: string;
      name: string;
      projectNumber: string;
      /** Format: date-time */
      projectSOP: string;
      description?: string;
      metrics: components['schemas']['MetricsDto'][];
      componentIds: number[];
    };
    MetricsDto: {
      /** Format: date-time */
      date?: string;
      basic?: number;
      basicWithPercent?: number;
    };
    ComponentDto: {
      /** Format: int64 */
      id?: number;
      /** Format: date-time */
      creationDate?: string;
      /** Format: date-time */
      updateDate?: string;
      number?: string;
      revision?: string;
      name?: string;
      material?: string;
      description?: string;
      processes?: components['schemas']['ProcessDto'][];
      documents?: components['schemas']['DocumentDto'][];
    };
    DocumentDto: {
      /** Format: int64 */
      id?: number;
      /** Format: date-time */
      creationDate?: string;
      /** Format: date-time */
      updateDate?: string;
      name?: string;
      description?: string;
      sourceUrl?: string;
    };
    ProjectDto: {
      /** Format: int64 */
      id?: number;
      /** Format: date-time */
      creationDate?: string;
      /** Format: date-time */
      updateDate?: string;
      /** Format: date-time */
      validFrom?: string;
      /** Format: date-time */
      validTo?: string;
      name?: string;
      projectNumber?: string;
      /** Format: date-time */
      projectSOP?: string;
      description?: string;
      metricsByDate?: Record<string, components['schemas']['MetricsDto']>;
      components?: components['schemas']['ComponentDto'][];
    };
    CreateProcessRequest: {
      name: string;
      description: string;
      disable: boolean;
    };
    CreateComponentRequest: {
      number: string;
      revision: string;
      name: string;
      material: string;
      description?: string;
      processesIds?: number[];
      documentIds?: number[];
    };
    CreateRefreshTokenRequest: {
      refreshToken: string;
    };
    AuthDto: {
      accessToken?: string;
      refreshToken?: string;
      tokenType?: string;
      user?: components['schemas']['UserDto'];
    };
    CreateAuthRequest: {
      login: string;
      password: string;
    };
    UpdateUserRequest: {
      /** Format: int64 */
      id: number;
      username: string;
      password: string;
      name?: string;
      surname?: string;
      email: string;
      disable: boolean;
      /** @enum {string} */
      role: 'ROLE_USER' | 'ROLE_ADMIN' | 'ROLE_MANAGER';
    };
    UpdateSupplierRequest: {
      /** Format: int64 */
      id: number;
      name: string;
      street: string;
      city: string;
      province: string;
      country: string;
      phoneNumber: string;
      emailAddress: string;
      disable: boolean;
      processesIds?: number[];
    };
    UpdateProjectRequest: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      validFrom: string;
      /** Format: date-time */
      validTo: string;
      name: string;
      projectNumber: string;
      /** Format: date-time */
      projectSOP: string;
      description?: string;
      metrics: components['schemas']['MetricsDto'][];
      componentIds?: number[];
    };
    UpdateProcessRequest: {
      /** Format: int64 */
      id: number;
      name: string;
      description: string;
      disable: boolean;
    };
    UpdateComponentRequest: {
      /** Format: int64 */
      id: number;
      number: string;
      revision: string;
      name: string;
      material: string;
      description?: string;
      processesIds?: number[];
      documentIds?: number[];
    };
    Pageable: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      sort?: string[];
    };
    PageUserDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['UserDto'][];
      /** Format: int32 */
      number?: number;
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      sort?: components['schemas']['SortObject'];
      empty?: boolean;
    };
    PageableObject: {
      /** Format: int64 */
      offset?: number;
      paged?: boolean;
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      pageSize?: number;
      sort?: components['schemas']['SortObject'];
      unpaged?: boolean;
    };
    SortObject: {
      empty?: boolean;
      sorted?: boolean;
      unsorted?: boolean;
    };
    PageSupplierDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['SupplierDto'][];
      /** Format: int32 */
      number?: number;
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      sort?: components['schemas']['SortObject'];
      empty?: boolean;
    };
    PageSimpleProjectDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['SimpleProjectDto'][];
      /** Format: int32 */
      number?: number;
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      sort?: components['schemas']['SortObject'];
      empty?: boolean;
    };
    SimpleProjectDto: {
      /** Format: int64 */
      id?: number;
      /** Format: date-time */
      creationDate?: string;
      /** Format: date-time */
      updateDate?: string;
      /** Format: date-time */
      validFrom?: string;
      /** Format: date-time */
      validTo?: string;
      name?: string;
      projectNumber?: string;
      /** Format: date-time */
      projectSOP?: string;
      description?: string;
    };
    PageProcessDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['ProcessDto'][];
      /** Format: int32 */
      number?: number;
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      sort?: components['schemas']['SortObject'];
      empty?: boolean;
    };
    PageDocumentDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['DocumentDto'][];
      /** Format: int32 */
      number?: number;
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      sort?: components['schemas']['SortObject'];
      empty?: boolean;
    };
    PageComponentDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['ComponentDto'][];
      /** Format: int32 */
      number?: number;
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      sort?: components['schemas']['SortObject'];
      empty?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getAllUsers: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['PageUserDto'];
        };
      };
    };
  };
  createUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['UserDto'];
        };
      };
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['UserDto'];
        };
      };
    };
  };
  getAllSuppliers: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['PageSupplierDto'];
        };
      };
    };
  };
  createSupplier: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSupplierRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['SupplierDto'];
        };
      };
    };
  };
  updateSupplier: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSupplierRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['SupplierDto'];
        };
      };
    };
  };
  getAllProjects: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['PageSimpleProjectDto'];
        };
      };
    };
  };
  createProject: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProjectRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['ProjectDto'];
        };
      };
    };
  };
  updateProject: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProjectRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['ProjectDto'];
        };
      };
    };
  };
  getAllProcesses: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['PageProcessDto'];
        };
      };
    };
  };
  createProcess: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProcessRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['ProcessDto'];
        };
      };
    };
  };
  updateProcess: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProcessRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['ProcessDto'];
        };
      };
    };
  };
  uploadFile: {
    parameters: {
      query: {
        name: string;
        description?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['DocumentDto'];
        };
      };
    };
  };
  getAllComponents: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['PageComponentDto'];
        };
      };
    };
  };
  createComponent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateComponentRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['ComponentDto'];
        };
      };
    };
  };
  updateComponent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateComponentRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['ComponentDto'];
        };
      };
    };
  };
  refreshToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRefreshTokenRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['AuthDto'];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAuthRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['AuthDto'];
        };
      };
    };
  };
  getUserById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['UserDto'];
        };
      };
    };
  };
  deleteUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content?: never;
      };
    };
  };
  getSupplierById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['SupplierDto'];
        };
      };
    };
  };
  deleteSupplier: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content?: never;
      };
    };
  };
  getProjectById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['ProjectDto'];
        };
      };
    };
  };
  deleteProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content?: never;
      };
    };
  };
  getProcessById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['ProcessDto'];
        };
      };
    };
  };
  deleteProcess: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content?: never;
      };
    };
  };
  getAllDocuments: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['PageDocumentDto'];
        };
      };
    };
  };
  getDocumentById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['DocumentDto'];
        };
      };
    };
  };
  delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content?: never;
      };
    };
  };
  previewFile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': string;
        };
      };
    };
  };
  downloadFile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': string;
        };
      };
    };
  };
  getComponentById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          '*/*': components['schemas']['ComponentDto'];
        };
      };
    };
  };
  deleteComponent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content?: never;
      };
    };
  };
}
